import { MetadataRoute } from "next";

export default function sitemap(): MetadataRoute.Sitemap {
  const base = "https://cornerstonepm.ai";
  const now = new Date();

  const routes = [
    { url: "/", priority: 1.0, changeFrequency: "weekly" as const },
    { url: "/features", priority: 0.9, changeFrequency: "weekly" as const },
    { url: "/pricing", priority: 0.9, changeFrequency: "monthly" as const },
    { url: "/usage-rates", priority: 0.8, changeFrequency: "monthly" as const },
    { url: "/beta", priority: 0.9, changeFrequency: "monthly" as const },
    { url: "/ai-features", priority: 0.9, changeFrequency: "weekly" as const },
    { url: "/ai-agents", priority: 0.8, changeFrequency: "weekly" as const },
    { url: "/foreman", priority: 0.8, changeFrequency: "weekly" as const },
    { url: "/brain", priority: 0.8, changeFrequency: "weekly" as const },
    { url: "/ai-takeoff", priority: 0.8, changeFrequency: "weekly" as const },
    { url: "/api-access", priority: 0.8, changeFrequency: "weekly" as const },
    { url: "/api-docs", priority: 0.8, changeFrequency: "weekly" as const },
    { url: "/jobsite-ai", priority: 0.9, changeFrequency: "weekly" as const },
    { url: "/construction", priority: 0.7, changeFrequency: "monthly" as const },
    { url: "/sales", priority: 0.7, changeFrequency: "monthly" as const },
    { url: "/purchasing", priority: 0.7, changeFrequency: "monthly" as const },
    { url: "/design", priority: 0.7, changeFrequency: "monthly" as const },
    { url: "/listing-sheet", priority: 0.7, changeFrequency: "monthly" as const },
    { url: "/compare", priority: 0.7, changeFrequency: "monthly" as const },
    { url: "/alternatives", priority: 0.8, changeFrequency: "monthly" as const },
    { url: "/qr", priority: 0.8, changeFrequency: "monthly" as const },
    { url: "/contact", priority: 0.6, changeFrequency: "yearly" as const },
    { url: "/faq", priority: 0.9, changeFrequency: "monthly" as const },
    { url: "/blog", priority: 0.7, changeFrequency: "weekly" as const },
    { url: "/blog/60-second-home-sale", priority: 0.6, changeFrequency: "yearly" as const },
    { url: "/blog/buildertrend-vs-cornerstone", priority: 0.6, changeFrequency: "yearly" as const },
    { url: "/blog/permitting-delays-home-builders", priority: 0.6, changeFrequency: "yearly" as const },
    { url: "/blog/spreadsheets-killing-schedule", priority: 0.6, changeFrequency: "yearly" as const },
    { url: "/blog/subcontractor-management-home-builders", priority: 0.6, changeFrequency: "yearly" as const },
    { url: "/blog/job-cost-tracking-home-builders", priority: 0.6, changeFrequency: "yearly" as const },
    { url: "/blog/ai-construction-management-software", priority: 0.7, changeFrequency: "monthly" as const },
    { url: "/blog/builder-ai-software", priority: 0.7, changeFrequency: "monthly" as const },
    { url: "/blog/homebuilding-ai", priority: 0.7, changeFrequency: "monthly" as const },
    { url: "/ai-construction-management", priority: 0.8, changeFrequency: "monthly" as const },
    { url: "/ai-for-home-builders", priority: 0.8, changeFrequency: "monthly" as const },
    { url: "/ai-scheduling", priority: 0.8, changeFrequency: "monthly" as const },
    { url: "/ai-new-home-sales", priority: 0.8, changeFrequency: "monthly" as const },
    { url: "/ai-construction-purchasing", priority: 0.8, changeFrequency: "monthly" as const },
    { url: "/blog/construction-purchase-order-software", priority: 0.7, changeFrequency: "monthly" as const },
    { url: "/blog/subcontractor-scheduling-software", priority: 0.7, changeFrequency: "monthly" as const },
    { url: "/blog/jobtread-alternative", priority: 0.7, changeFrequency: "monthly" as const },
    { url: "/permitting", priority: 0.8, changeFrequency: "monthly" as const },
    { url: "/home-builder-project-management-software", priority: 0.9, changeFrequency: "monthly" as const },
    { url: "/buildertrend-alternative", priority: 0.8, changeFrequency: "monthly" as const },
    { url: "/newstar-alternative", priority: 0.8, changeFrequency: "monthly" as const },
    { url: "/buildpro-alternative", priority: 0.8, changeFrequency: "monthly" as const },
    { url: "/kova-alternative", priority: 0.8, changeFrequency: "monthly" as const },
    { url: "/marksystems-alternative", priority: 0.8, changeFrequency: "monthly" as const },
    { url: "/hyphen-alternative", priority: 0.8, changeFrequency: "monthly" as const },
    { url: "/blog/home-builder-software-buyer-guide-2026", priority: 0.7, changeFrequency: "monthly" as const },
    { url: "/blog/migrating-from-buildertrend-to-cornerstone", priority: 0.7, changeFrequency: "monthly" as const },
    { url: "/blog/newstar-implementation-cost-breakdown", priority: 0.7, changeFrequency: "monthly" as const },
    { url: "/blog/production-builder-vs-custom-builder-software", priority: 0.7, changeFrequency: "monthly" as const },
    { url: "/about", priority: 0.6, changeFrequency: "yearly" as const },
    { url: "/bid-import-ai", priority: 0.8, changeFrequency: "monthly" as const },
    { url: "/migrate", priority: 0.8, changeFrequency: "monthly" as const },
    { url: "/support-ai", priority: 0.7, changeFrequency: "monthly" as const },
    { url: "/blog/design-center-home-builder", priority: 0.7, changeFrequency: "monthly" as const },
    { url: "/blog/new-home-sales-pipeline", priority: 0.7, changeFrequency: "monthly" as const },
    { url: "/blog/buildertrend-vs-cornerstone-feature-comparison", priority: 0.7, changeFrequency: "monthly" as const },
    { url: "/blog/jobtread-vs-cornerstone-pm-production-home-builders", priority: 0.7, changeFrequency: "monthly" as const },
    { url: "/blog/ai-takeoff-vs-manual-takeoff-cost", priority: 0.7, changeFrequency: "monthly" as const },
    { url: "/blog/buildpro-vs-cornerstone-modern-stack", priority: 0.7, changeFrequency: "monthly" as const },
    { url: "/blog/how-to-choose-home-builder-software", priority: 0.7, changeFrequency: "monthly" as const },
    { url: "/blog/why-small-builders-cant-afford-newstar", priority: 0.7, changeFrequency: "monthly" as const },
    { url: "/blog/buildertrend-pricing-true-cost", priority: 0.7, changeFrequency: "monthly" as const },
    { url: "/blog/foreman-ai-83-skills", priority: 0.7, changeFrequency: "monthly" as const },
    { url: "/blog/foreman-ai-100-skills", priority: 0.8, changeFrequency: "monthly" as const },
    { url: "/blog/foreman-ai-75-action-loop", priority: 0.8, changeFrequency: "monthly" as const },
    { url: "/blog/how-blueprint-ai-extracts-material-scopes", priority: 0.7, changeFrequency: "monthly" as const },
    { url: "/blog/cornerstone-pm-vs-procore-residential-home-builder", priority: 0.7, changeFrequency: "monthly" as const },
    { url: "/blog/cornerstone-pm-vs-acculynx-home-builder-software", priority: 0.7, changeFrequency: "monthly" as const },
    { url: "/blog/coconstruct-vs-cornerstone-production-design-center", priority: 0.7, changeFrequency: "monthly" as const },
    { url: "/blog/contractor-foreman-vs-cornerstone-production-builder", priority: 0.7, changeFrequency: "monthly" as const },
    { url: "/blog/buildxact-vs-cornerstone-selections-vs-design-center", priority: 0.7, changeFrequency: "monthly" as const },
    { url: "/blog/auto-quantity-scope-items-home-builder", priority: 0.7, changeFrequency: "monthly" as const },
    { url: "/blog/auto-quantity-scope-items-square-footage", priority: 0.7, changeFrequency: "monthly" as const },
    { url: "/blog/foreman-ai-memory-construction-software", priority: 0.7, changeFrequency: "monthly" as const },
    { url: "/blog/cornerstone-pm-vs-jobnimbus-home-builder-software", priority: 0.7, changeFrequency: "monthly" as const },
    { url: "/blog/design-center-exclusion-groups-pick-one", priority: 0.7, changeFrequency: "monthly" as const },
    { url: "/blog/structural-options-pricing-floorplan-sqft", priority: 0.7, changeFrequency: "monthly" as const },
    { url: "/blog/fieldwire-vs-cornerstone-pm-home-builder", priority: 0.7, changeFrequency: "monthly" as const },
    { url: "/blog/clickup-monday-construction-vs-home-builder-software", priority: 0.7, changeFrequency: "monthly" as const },
    { url: "/blog/webhook-events-construction-software-automation", priority: 0.7, changeFrequency: "monthly" as const },
    { url: "/blog/crm-migration-wizard-switch-construction-software", priority: 0.7, changeFrequency: "monthly" as const },
    { url: "/blog/api-operations-construction-software-ai-agents", priority: 0.8, changeFrequency: "monthly" as const },
    { url: "/blog/vendor-bid-requests-portal-no-login", priority: 0.7, changeFrequency: "monthly" as const },
    { url: "/blog/foreman-ai-product-image-web-scraping", priority: 0.7, changeFrequency: "monthly" as const },
    { url: "/blog/enterprise-multi-division-home-builder-software", priority: 0.7, changeFrequency: "monthly" as const },
    { url: "/blog/knowify-vs-cornerstone-production-home-builder", priority: 0.7, changeFrequency: "monthly" as const },
    { url: "/blog/construction-ai-context-memory-long-sessions", priority: 0.7, changeFrequency: "monthly" as const },
    { url: "/blog/promote-standard-finish-to-upgrade-design-center", priority: 0.7, changeFrequency: "monthly" as const },
    { url: "/blog/bid-import-ai-takeoff-pricing-modes", priority: 0.7, changeFrequency: "monthly" as const },
    { url: "/blog/hidden-cost-switching-construction-software-migration", priority: 0.7, changeFrequency: "monthly" as const },
    { url: "/blog/mcp-server-construction-software-claude-cursor", priority: 0.8, changeFrequency: "monthly" as const },
    { url: "/blog/construction-software-data-export-backup-no-lock-in", priority: 0.7, changeFrequency: "monthly" as const },
    { url: "/blog/asana-vs-home-builder-construction-software", priority: 0.7, changeFrequency: "monthly" as const },
    { url: "/blog/designer-packages-curated-selections-home-builders", priority: 0.7, changeFrequency: "monthly" as const },
    { url: "/blog/construction-ai-knowledge-base-estimating-formulas", priority: 0.7, changeFrequency: "monthly" as const },
    { url: "/blog/construction-allowances-master-cost-budget-home-builders", priority: 0.7, changeFrequency: "monthly" as const },
    { url: "/blog/foreman-ai-vision-jobsite-photo-analysis-construction", priority: 0.7, changeFrequency: "monthly" as const },
    { url: "/blog/houzz-pro-vs-cornerstone-production-home-builder", priority: 0.7, changeFrequency: "monthly" as const },
    { url: "/blog/option-classes-scope-linked-design-options-home-builders", priority: 0.7, changeFrequency: "monthly" as const },
    { url: "/blog/true-cost-of-spreadsheet-budgets-home-builders", priority: 0.7, changeFrequency: "monthly" as const },
    { url: "/blog/ai-mls-listing-generator-home-builders", priority: 0.7, changeFrequency: "monthly" as const },
    { url: "/blog/foreman-ai-agent-takes-actions-not-chatbot", priority: 0.7, changeFrequency: "monthly" as const },
    { url: "/blog/community-vendor-bid-awards-not-lowest-bid", priority: 0.7, changeFrequency: "monthly" as const },
    { url: "/blog/foreman-ai-profitability-budget-reports-vendor-scorecards", priority: 0.7, changeFrequency: "monthly" as const },
    { url: "/blog/real-vendor-pricing-no-estimator-fudging", priority: 0.7, changeFrequency: "monthly" as const },
    { url: "/blog/marksystems-vs-cornerstone-production-builder", priority: 0.7, changeFrequency: "monthly" as const },
    { url: "/blog/quickbooks-online-home-builder-auto-sync", priority: 0.7, changeFrequency: "monthly" as const },
    { url: "/blog/home-builder-sales-pipeline-crm-software", priority: 0.7, changeFrequency: "monthly" as const },
    { url: "/blog/quickbooks-online-sync-home-builder-construction", priority: 0.7, changeFrequency: "monthly" as const },
    { url: "/blog/auto-bill-batch-pay-construction-accounts-payable", priority: 0.7, changeFrequency: "monthly" as const },
    { url: "/blog/stop-double-entering-pos-quickbooks-home-builders", priority: 0.7, changeFrequency: "monthly" as const },
    { url: "/blog/sage-300-cre-vs-cornerstone-home-builder-software", priority: 0.7, changeFrequency: "monthly" as const },
    { url: "/blog/hard-cost-rule-vendor-priced-budgets-no-fudging", priority: 0.7, changeFrequency: "monthly" as const },
    { url: "/blog/foreman-ai-build-area-costs-by-chat-construction", priority: 0.7, changeFrequency: "monthly" as const },
    { url: "/blog/quickbooks-purchase-order-bill-accrual-home-builders", priority: 0.7, changeFrequency: "monthly" as const },
    { url: "/blog/automatic-sales-tax-materials-labor-exempt-construction", priority: 0.7, changeFrequency: "monthly" as const },
    { url: "/blog/scope-first-budgeting-organize-costs-by-trade-home-builders", priority: 0.7, changeFrequency: "monthly" as const },
    { url: "/blog/buildermt-vs-cornerstone-production-home-builder", priority: 0.7, changeFrequency: "monthly" as const },
    { url: "/blog/home-builder-accounting-project-management-one-platform", priority: 0.7, changeFrequency: "monthly" as const },
    { url: "/blog/vendor-payment-schedules-net-terms-semi-monthly-home-builders", priority: 0.7, changeFrequency: "monthly" as const },
    { url: "/blog/quickbooks-sync-audit-trail-construction-accounting", priority: 0.7, changeFrequency: "monthly" as const },
    { url: "/blog/cascade-scheduling-construction-delays-home-builders", priority: 0.7, changeFrequency: "monthly" as const },
    { url: "/blog/jobtread-vs-cornerstone-production-home-builder", priority: 0.7, changeFrequency: "monthly" as const },
    { url: "/blog/home-builder-design-center-software-what-it-should-do", priority: 0.7, changeFrequency: "monthly" as const },
    { url: "/blog/punch-list-management-home-builders-ai", priority: 0.7, changeFrequency: "monthly" as const },
    { url: "/blog/change-order-management-production-home-builders", priority: 0.7, changeFrequency: "monthly" as const },
    { url: "/blog/construction-chart-of-accounts-cost-codes-home-builders", priority: 0.7, changeFrequency: "monthly" as const },
    { url: "/blog/premier-construction-software-vs-cornerstone-home-builders", priority: 0.7, changeFrequency: "monthly" as const },
    { url: "/blog/construction-schedule-templates-home-builders", priority: 0.7, changeFrequency: "monthly" as const },
    { url: "/blog/bid-leveling-side-by-side-vendor-comparison-home-builders", priority: 0.7, changeFrequency: "monthly" as const },
    { url: "/blog/ai-scope-of-work-generation-subcontractors-home-builders", priority: 0.7, changeFrequency: "monthly" as const },
    { url: "/blog/why-subcontractors-ignore-bid-requests-home-builders", priority: 0.7, changeFrequency: "monthly" as const },
    { url: "/blog/uda-constructiononline-vs-cornerstone-production-home-builder", priority: 0.7, changeFrequency: "monthly" as const },
    { url: "/blog/construction-notification-preferences-role-based-alerts-home-builders", priority: 0.7, changeFrequency: "monthly" as const },
    { url: "/blog/construction-software-user-seats-who-needs-a-login", priority: 0.7, changeFrequency: "monthly" as const },
    { url: "/blog/vendor-jobsite-qr-check-in-gps-weather-home-builders", priority: 0.7, changeFrequency: "monthly" as const },
    { url: "/blog/model-home-qr-lead-capture-home-builder-sales", priority: 0.7, changeFrequency: "monthly" as const },
    { url: "/blog/bulk-create-design-options-parts-catalog-home-builders", priority: 0.7, changeFrequency: "monthly" as const },
    { url: "/blog/plan-set-to-purchase-order-ai-takeoff-home-builders", priority: 0.7, changeFrequency: "monthly" as const },
    { url: "/blog/smartsheet-vs-cornerstone-home-builder-construction", priority: 0.7, changeFrequency: "monthly" as const },
    { url: "/blog/same-floorplan-two-communities-different-costs-home-builders", priority: 0.7, changeFrequency: "monthly" as const },
    { url: "/blog/quickbooks-transaction-memos-job-costing-detail-home-builders", priority: 0.7, changeFrequency: "monthly" as const },
  ];

  return routes.map((route) => ({
    url: `${base}${route.url}`,
    lastModified: now,
    changeFrequency: route.changeFrequency,
    priority: route.priority,
  }));
}
